#!/usr/bin/env bash
includes=()
outs=()
args=()

for arg in $@; do
    case $arg in
        -I*|--proto_path=*)
            includes+=("$arg")
            ;;
        --bq-schema_out=*)
            outs+=("$arg")
            includes+=("-I/usr/include/github.com/googlecloudplatform/protoc-gen-bq-schema")
            ;;
        --gorm_out=*)
            outs+=("$arg")
            includes+=("-I/usr/include/github.com/infobloxopen/protoc-gen-gorm")
            ;;
        --*_out=*)
            outs+=("$arg")
            ;;
        *)
            args+=("$arg")
            ;;
    esac
done

if [ ${#includes[@]} -eq 0 ]; then
    includes+=("-I.")
fi

protoc_cmd=(protoc "${includes[@]}" "${outs[@]}" "${args[@]}")
exec "${protoc_cmd[@]}"
