name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 0'

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: renovatebot/github-action@v34.51.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
